---
- name: Deploy Spring Petclinic as Linux Service
  hosts: appserver
  become: yes
  tasks:
    - name: Fail the execution when distribution is not ubuntu
      fail:
        msg: This playbook only work on Ubuntu Distribution. support for other OS will be comming soon.
      when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "CentOS"
    - name: Update ubuntu packages and install java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      notify:
        - debug message for java
      when: ansible_facts['distribution'] == "Ubuntu"  
    - name: install java
      yum:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      notify:
        - debug message for java
      when: ansible_facts['distribution'] == "CentOS"
    - name: Creating spring petclinic directory
      file:
        path: "{{ app_dir }}"
        state: directory
      notify: 
        - debug message for directory creation
    - name: Download Spring Petclinic
      get_url:
        url: "{{ app_download_url }}"
        dest: "{{ app_file_name }}"
      notify: 
        - debug Message for download spring petclinic
    - name: Create Spring Bootuser
      user:
        name: "{{ user_name }}"
        password: "{{ user_name }}"
        state: present
      notify: 
        - Change ownership of jar file  
    - name: Copy the file From Local Machine To Remote spring petlinic service
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: Enable and start spring petclinic service
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started
  handlers:
    - name: Change ownership of jar file
      file:
        path: "{{ app_file_name }}"
        owner: "{{ user_name }}"
        mode: '500'
        state: file

    - name: debug message for java
      debug:
        msg: Java with paackage {{ java_package }} is installed

    - name: debug message for directory creation
      debug:
        msg: Directory created at {{ app_dir }}. 

    - name: debug Message for download spring petclinic
      debug:
        msg: file downloaded at {{ app_file_name }} location 

    