---
- name: Deploy Spring Petclinic as Linux Service
  hosts: appserver
  become: yes
  vars:
    java_packages: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic
    app_download_url: https://springpetclinicservice.s3.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file_name: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    user_name: springbootuser
  tasks:
    - name: Update ubuntu packages and install java
      apt:
        name: "{{ java_packages }}"
        update_cache: yes
        state: present
    - name: Creating spring petclinic directory
      file:
        path: "{{ app_dir }}"
        state: directory
    - name: Download Spring Petclinic
        get_url: "{{ app_download_url }}"
        dest: "{{ app_file_name }}"
    - name: Create Spring Bootuser
      user:
        name: "{{ user_name }}"
        password: "{{ user_name }}"
        state: present
    - name: Change ownership of file
      file:
        path: "{{ app_file_name }}"
        owner: "{{ user_name }}"
        mode: '500'
        state: file
    - name: Copy the file From Local Machine To Remote spring petlinic service
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: Enable and start spring petclinic service
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started