---
# tasks file for role_skeleton
- name: Fail the execution when distribution is not ubuntu and centos
  fail:
    msg: This playbook only work on Ubuntu Distribution. support for other OS will be comming soon.
  when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "CentOS"
  
- name: Installing apache 2
  package:
    name: "{{ apache_package }}"
    state: present
  notify:
    - log install apache server

- name: Install php package
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ php_package }}"
  notify:
    - log install php package

- name: Copy the php.info page
  copy:
    src: info.php
    dest: "{{ info_page_path }}"
  notify:
    - log info page copied
    - restart apache

- name: Start service httpd, if not started
  service:
    name: "{{ apache_package }}"
    enabled: yes
    state: started
